#!/usr/bin/env bash
# Bash script that configures a new
# Ubuntu machine to respect

apt-get -y update
apt-get -y install nginx
ufw allow "NGINX HTTP"
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart
