#!/usr/bin/python3

"""
    A python script that uses REST API for a given employee ID
    returns his/her TODO list progress
"""


if __name__ == "__main__":
    import requests
    import json

    url = "https://jsonplaceholder.typicode.com/users"
    
    users = requests.get(url)
    data = users.text

    with open('gather.json', 'w') as file:
        json.dump(data, file)
