#!/usr/bin/env bash
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

num=1

while [ $num -le 100 ];
do
	if [ $((num%5)) -eq 0 ] && [ $((num%3)) -eq 0 ];
	then
		echo "FizzBuzz"
	elif [ $((num%3)) -eq 0 ];
	then
		echo "Fizz"
	elif [ $((num%5)) -eq 0 ];
	then
		echo "Buzz"
	else
		echo "$num"
	fi
	(( num++ ))
done
